#!/usr/bin/env bash
# =============================================================================
# mailcow backup -> IDrive e2 (S3) via restic
#
# Pipeline:
#   1. mailcow official backup script (helper-scripts/backup_and_restore.sh)
#      creates a consistent snapshot of ALL components (vmail, crypt, redis,
#      rspamd, postfix, MySQL/MariaDB) into a local staging directory
#   2. restic pushes the snapshot folder to IDrive e2
#   3. restic pushes mailcow configuration (mailcow.conf, custom configs,
#      TLS certs, hooks) tagged separately
#   4. retention policy is applied (forget + prune)
#   5. old local staging folders are cleaned up
#
# Config:  /opt/mailcow-backup/mailcow-backup.env
# Run:     sudo /opt/mailcow-backup/backup.sh
# =============================================================================
set -euo pipefail

BACKUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${BACKUP_DIR}/mailcow-backup.env"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} not found." >&2
  exit 1
fi
# shellcheck source=/dev/null
source "${ENV_FILE}"

# --- sanity checks ----------------------------------------------------------
if [[ "${E2_ACCESS_KEY:-}" == "CHANGE_ME"* || "${E2_SECRET_KEY:-}" == "CHANGE_ME"* || "${RESTIC_PASSWORD:-}" == "CHANGE_ME"* ]]; then
  echo "ERROR: edit ${ENV_FILE} and set your IDrive e2 credentials and restic password first." >&2
  exit 1
fi
if [[ -z "${RESTIC_REPOSITORY:-}" ]]; then
  echo "ERROR: RESTIC_REPOSITORY is empty in ${ENV_FILE}." >&2
  exit 1
fi

MAILCOW_DIR="${MAILCOW_INSTALL_DIR:-/opt/mailcow-dockerized}"
STAGING_DIR="${BACKUP_STAGING_DIR:-/var/backups/mailcow}"
RESTIC_IMAGE="${RESTIC_IMAGE:-restic/restic:latest}"
BACKUP_HOST="${RESTIC_HOSTNAME:-$(hostname)}"
THREADS="${BACKUP_THREADS:-$(nproc)}"
LOCAL_KEEP_DAYS="${BACKUP_LOCAL_KEEP_DAYS:-3}"

RESTIC_ENV=(
  -e "RESTIC_REPOSITORY=${RESTIC_REPOSITORY}"
  -e "RESTIC_PASSWORD=${RESTIC_PASSWORD}"
)
AWS_ENV=(
  -e "AWS_ACCESS_KEY_ID=${E2_ACCESS_KEY}"
  -e "AWS_SECRET_ACCESS_KEY=${E2_SECRET_KEY}"
)
if [[ -n "${AWS_DEFAULT_REGION:-}" ]]; then
  AWS_ENV+=(-e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}")
fi

# Volumes used for the data/config backup steps (read-only for backup)
RESTIC_MOUNTS=(
  -v "${STAGING_DIR}:/data:ro"
  -v "${MAILCOW_DIR}:/mailcow:ro"
  -v "${BACKUP_DIR}:/mailcow-backup:ro"
)

log() { echo "[$(date '+%F %T')] $*"; }

run_restic() {
  local -a extra=()
  if [[ -n "${RESTIC_EXTRA_OPTS:-}" ]]; then
    read -r -a extra <<< "${RESTIC_EXTRA_OPTS}"
  fi
  docker run --rm \
    "${RESTIC_ENV[@]}" \
    "${AWS_ENV[@]}" \
    "${RESTIC_MOUNTS[@]}" \
    "${RESTIC_IMAGE}" \
    "${extra[@]}" \
    "$@"
}

# --- 1. mailcow internal backup (all components) -----------------------------
[[ -d "${MAILCOW_DIR}" ]] || { echo "ERROR: ${MAILCOW_DIR} not found" >&2; exit 1; }
mkdir -p "${STAGING_DIR}"
chmod 775 "${STAGING_DIR}"

log "Step 1/5: mailcow internal backup (all components) -> ${STAGING_DIR}"
export MAILCOW_BACKUP_LOCATION="${STAGING_DIR}"
export THREADS="${THREADS}"
cd "${MAILCOW_DIR}"
"${MAILCOW_DIR}/helper-scripts/backup_and_restore.sh" backup all

LATEST="$(ls -1dt "${STAGING_DIR}"/mailcow-* 2>/dev/null | head -n1 || true)"
if [[ -z "${LATEST}" ]]; then
  echo "ERROR: no backup folder was produced by the mailcow backup script" >&2
  exit 1
fi
log "Backup folder: ${LATEST}"

# --- 2. restic: repository init + upload -------------------------------------
log "Step 2/5: ensure restic repository is initialized (${RESTIC_REPOSITORY})"
if ! run_restic snapshots >/dev/null 2>&1; then
  run_restic init
fi

log "Step 3/5: uploading backup to IDrive e2"
run_restic backup \
  --host "${BACKUP_HOST}" \
  --tag mailcow \
  "/data/$(basename "${LATEST}")"

log "Step 3b/5: uploading mailcow configuration (tag: mailcow-config)"
# data/web is regenerated by mailcow updates; ssl-example is a template.
run_restic backup \
  --host "${BACKUP_HOST}" \
  --tag mailcow-config \
  --exclude "/mailcow/data/web" \
  --exclude "/mailcow/data/assets/ssl-example" \
  /mailcow \
  /mailcow-backup

# --- 3. retention ------------------------------------------------------------
log "Step 4/5: applying retention policy (forget + prune)"
run_restic forget \
  --host "${BACKUP_HOST}" \
  --keep-daily  "${RESTIC_KEEP_DAILY:-7}" \
  --keep-weekly "${RESTIC_KEEP_WEEKLY:-4}" \
  --keep-monthly "${RESTIC_KEEP_MONTHLY:-12}" \
  --keep-yearly  "${RESTIC_KEEP_YEARLY:-2}" \
  --prune

# --- 4. local cleanup ----------------------------------------------------------
log "Step 5/5: cleaning local staging (keeping ${LOCAL_KEEP_DAYS} days)"
find "${STAGING_DIR}"/mailcow-* -maxdepth 0 -mmin +$((LOCAL_KEEP_DAYS * 1440)) -exec rm -rf {} + 2>/dev/null || true

# --- 5. summary -----------------------------------------------------------------
log "Backup complete. Latest snapshots in the restic repository:"
run_restic snapshots --latest --compact
